server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: sc-gateway-webflux
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # =====================================
        - id: mock
          uri: http://localhost:9806
          predicates:
            - Path=/mock/**
        # =====================================
        - id: SERVICE-HI
          uri: lb://SERVICE-HI
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
